// <auto-generated />
namespace PharmacyWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update001));
        
        string IMigrationMetadata.Id
        {
            get { return "201811201336316_update001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
