// <auto-generated />
namespace PharmacyWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update015));
        
        string IMigrationMetadata.Id
        {
            get { return "201812161909103_update015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
